company/urls.py
from django.conf.urls import include, url
from . import views

app_name = "company"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'logout/$', views.logout, name="logout"),
]

hamrofare/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('company/', include('company.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from . import views

app_name = "main"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'signup/$', views.signup, name="signup"),
    url(r'login/$', views.login, name="login")
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'logout/$', views.logout, name="logout"),
]

company/models.py
from django.db import models

class Company(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length = 50)
    email = models.CharField(max_length = 100)
    contact = models.BigIntegerField()
    password = models.CharField(max_length = 20)
    company_name = models.CharField(max_length=50)
    bus_no = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.company_name

class Device(models.Model):
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE)
    vehicle_no = models.PositiveSmallIntegerField()
    enter_device_id = models.CharField(max_length = 20)
    exit_device_id = models.CharField(max_length = 20)
    balance = models.PositiveSmallIntegerField()
    owner = models.CharField(max_length = 20)

    def __str__(self):
        return self.owner

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 100)
    contact = models.BigIntegerField()
    address = models.CharField(max_length = 50)
    card_key = models.CharField(max_length = 16)
    blood_group = models.CharField(max_length = 3)
    user_type = models.CharField(max_length = 20)
    register_date = models.DateField()
    password = models.CharField(max_length = 20)
    is_new = models.BooleanField(default = True)
    def __str__(self):
        return self.name + ' - ' + self.card_key

class Transaction(models.Model):
    card_key = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.CharField(max_length = 20)
    end = models.CharField(max_length = 20)
    fare = models.PositiveSmallIntegerField()
    distance = models.PositiveSmallIntegerField()
    is_active = models.BooleanField(default = False)
    device_id = models.BigIntegerField()

    def __str__(self):
        return self.start

class Card(models.Model):
    card_key = models.ForeignKey(User, on_delete=models.CASCADE)
    expiry_date = models.DateField()
    created_date = models.DateField()
    balance = models.PositiveIntegerField()
    card_type = models.CharField(max_length = 20)

    def __str__(self):
        return self.card_type

company/views.py
from typing import Dict, Any
from django.shortcuts import render, redirect ,get_object_or_404
from user.models import User, Transaction, Card
from company.models import Company, Device

def index(request):
    if 'user' in request.session and 'acountType' in request.session == 'company':
        user = Company.objects.get(username=request.session['user'])
        return render(request, 'company/index.html', {'user': user})
    elif 'user' in request.session and 'acountType' in request.session == 'user':
        user = User.objects.get(name=request.session['user'])
        return render(request, 'user/index.html', {'user': user})
    return redirect('main:index')




def logout(request):
    if 'user' in request.session:
        del request.session['user']
        del request.session['accountType']
    return redirect('main:index')

main/views.py
from typing import Dict, Any
from django.shortcuts import render, get_object_or_404, redirect
from user.models import User, Transaction, Card
from company.models import Company, Device
from datetime import datetime
import random


def index(request):
    if 'user' in request.session and 'acountType' in request.session == 'user':
        user = User.objects.get(name=request.session['user'])
        return render(request, 'user/index.html', {'user': user})
    elif 'user' in request.session and 'accountType' in request.session == 'company':
        user = Company.objects.get(username=request.session['user'])
        return render(request, 'company/index.html', {'user': user})
    return render(request, 'main/index.html')

def signup(request):
    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        contact = request.POST["contact"]
        address = request.POST["address"]
        bloodGroup = request.POST["bloodGroup"]
        userType = request.POST["userType"]
        password = request.POST["password1"]

        data = User()
        data.name = name
        data.email = email
        data.contact = contact
        data.address = address
        data.card_key = '%4x' % random.getrandbits(4*4) + '-' + '%4x' % random.getrandbits(4*4) + '-' + '%4x' % random.getrandbits(4*4) + '-' + '%4x' % random.getrandbits(4*4)
        data.blood_group = bloodGroup
        data.user_type = userType
        data.password = password
        data.register_date = datetime.now()
        data.save()

    return render(request, 'main/index.html')

def login(request):
    if request.method == 'POST':
        accountType = request.POST['accountType']

        if accountType == 'user':
            name = request.POST['userName']
            password = request.POST['password']
            accountType = request.POST['accountType']
            user = User.objects.filter(name=name, password=password)
            if not user:
                err_msg = "Login Invalid"
                context = {'err_msg': err_msg}
                return render(request, 'main/index.html', context)
            user = User.objects.get(name=name, password=password)

            request.session['user'] = name
            request.session['accountType'] = accountType
            print(request.session['user'])
            print(request.session['accountType'])
            return render(request, 'user/index.html', {'user': user})
        else:
            name = request.POST['userName']
            password = request.POST['password']
            accountType = request.POST['accountType']
            user = Company.objects.filter(username=name, password=password)
            if not user:
                err_msg = "Login Invalid"
                context = {'err_msg': err_msg}
                return render(request, 'main/index.html', context)
            user = Company.objects.get(username=name, password=password)

            request.session['user'] = name
            request.session['accountType'] = accountType
            print(request.session['user'])
            print(request.session['accountType'])
            return render(request, 'company/index.html', {'user': user})

user/views.py
from typing import Dict, Any
from django.shortcuts import render, redirect, get_object_or_404
from user.models import User, Transaction, Card
from company.models import Company, Device

def index(request):
    if 'user' in request.session and 'acountType' in request.session == 'user':
        user = User.objects.get(name=request.session['user'])
        return render(request, 'user/index.html', {'user': user})
    elif 'user' in request.session and 'acountType' in request.session == 'company':
        user = Company.objects.get(username=request.session['user'])
        return render(request, 'company/index.html', {'user': user})
    return redirect('main:index')



def logout(request):
    if 'user' in request.session:
        del request.session['user']
        del request.session['accountType']
    return redirect('main:index')

company/templates/company/index.html
<!doctype html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>HamroFare</title>
        <link rel="icon" href="{% static 'main/pix/logo.png' %}">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/admin-layout.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/floating-labels.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/index.css' %}">
    </head>
    <body>
        <nav id="header">
            <div class="logo">
                <a href="#"><img src="{% static 'main/pix/logo.png' %}" alt="logo" id="logo"></a>
            </div>
            <div id="banner">
                Hamro<font id="bannerTitle">Fare</font>
            </div>
            <ul>
                <a href="{% url 'company:logout' %}"><li>LOGOUT</li></a>
            </ul>
        </nav>

    <div class="container-fluid" id="wrapper">
        <div class="jumbotron" align="center">
            <div class="alert alert-success"><h1>Your Travel Partner</h1></div>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispUserDetail()">User Detail</button>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispVehicleInfo()">Vehicle Info</button>
			<div id = "userDetail">
                <br>
				<table class="table table-striped table-hover">
                    <tr>
                        <th>S.N</th>
                        <th>Company Owner</th>
                        <th>No. of vehicle</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>{{ user.company_name }}</td>
                        <td>{{ user.bus_no }}</td>           
                    </tr>
                </table>
			</div> 
			<div id = "vehicleInfo">
                <br>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>S.N</th>
                        <th>Owner</th>
                        <th>Vehicle No.</th>
                        <th>Entry Device id</th>
                        <th>Exit Device id</th>
                    </tr>
			        {% for vehicle in user.device_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ vehicle.owner }}</td>
                        <td>{{ vehicle.vehicle_no }}</td>           
                        <td>{{ vehicle.enter_device_id }}</td>
                        <td>{{ vehicle.exit_device_id }}</td>
                    </tr>
                    {% endfor %}
                </table>
			</div> 
		</div>   
	</div>
	        <!-- body end-->
	<div id="goUp">
            <a href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'smooth');">Up</a>
    </div>
        <footer>
            &copy; 2019 Copyright The Invictus Code
            <br>
            theinvictuscode@gmail.com
            <br>
            KTM, Nepal
        </footer>
     </body>
</html>
<!-- scripts -->
<script src="{% static 'main/js/layout.js' %}"></script>       
<script type="text/javascript">
    function dispUserDetail()
    {
        userDetail=document.getElementById('userDetail');
        vehicleInfo=document.getElementById('vehicleInfo');

        userDetail.style.display = "block";
        vehicleInfo.style.display = "none";
    }
    function dispVehicleInfo()
    {
        userDetail=document.getElementById('userDetail');
        vehicleInfo=document.getElementById('vehicleInfo');

        userDetail.style.display = "none";
        vehicleInfo.style.display = "block";
    }
</script>

main/templates/main/index.html
<!doctype html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>HamroFare</title>
        <link rel="icon" href="{% static 'main/pix/logo.png' %}">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/layout.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/floating-labels.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/index.css' %}">
        
    </head>
    <body>
        <nav id="header">
            <div class="logo">
                <a href="#"><img src="{% static 'main/pix/logo.png' %}" alt="logo" id="logo"></a>
            </div>
            <div id="banner">
                Hamro<font id="bannerTitle">Fare</font>
            </div>
        </nav>

        <!-- body -->
        <div class="container-fluid" id="wrapper">
        <div class="jumbotron" align="center">
            <div class="alert alert-success"><h1>" Your Travel Partner! "</h1></div>
            {% if err_msg %}
                <div class="alert alert-warning"><h1>{{ err_msg }}</h1></div>
            {% endif %}
            <button class="btn btn-lg btn-outline-secondary" onclick="dispLogin()">LogIn</button>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispSignup()">SignUp</button>
            <div id="LogIn">
                <form class="form" method="post" action="{% url 'main:login' %}" onsubmit="return checklogin()">
                    {% csrf_token %}
                  <div class="form-label-group">
                    <input type="text" id="userName" name="userName" class="form-control" placeholder="Username" autofocus>
                    <label for="userName">Username</label>
                  </div>
                  <div class="form-label-group">
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password" autofocus>
                    <label for="password">Password</label>
                  </div>
                  <div class="form-label-group">
                    <select name="accountType" id="accountType" class="form-control">
                      <option value="0">Select Account Type</option>
                      <option value="user">User</option>
                      <option value="company">Company</option>
                    </select>
                  </div>
                  <input class="btn btn-lg btn-primary btn-block" type="submit" value="LogIn">
                </form>
            </div>
            <div id="SignUp">
                <form class="form" method="post" action="{% url 'main:signup' %}" onsubmit="return checksignupuser()">
                    {% csrf_token %}
                    <div class="form-label-group">
                        <input type="text" id="name" name="name" class="form-control" placeholder="Name" autofocus>
                        <label for="name">Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="email" id="email" name="email" class="form-control" placeholder="Email address" autofocus>
                        <label for="email">Email address</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" id="contact" name="contact" class="form-control" placeholder="Contact" autofocus>
                        <label for="contact">Contact</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" id="address" name="address" class="form-control" placeholder="Address" autofocus>
                        <label for="address">Address</label>
                    </div>                 
                    <div class="form-label-group">
                        <select name="bloodGroup" id="bloodGroup" class="form-control">
                            <option value="0">Select blood group</option>
                            <option value="A+">A+</option>
                            <option value="A-">A-</option>
                            <option value="B+">B+</option>
                            <option value="B-">B-</option>
                            <option value="AB+">AB+</option>
                            <option value="AB-">AB-</option>
                            <option value="O+">O+</option>
                            <option value="O-">O-</option>
                        </select>
                    </div>
                    <div class="form-label-group">
                        <select name="userType" id="userType" class="form-control">
                            <option value="0">Select User Type</option>
                            <option value="General">General</option>
                            <option value="Student">Student</option>
                            <option value="Elderly">Elderly</option>
                            <option value="Differently Able">Differently Able</option>
                        </select>
                    </div>
                    <div class="form-label-group">
                        <input type="password" id="password1" name="password1" class="form-control" placeholder="Password" autofocus>
                        <label for="password1">Password</label>
                    </div>
                    <div class="form-label-group">
                        <input type="password" id="password2" name="password2" class="form-control" placeholder="Re-enter-Password" autofocus>
                        <label for="password2">Re-enter-Password</label>
                    </div>
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="SignUp">
                </form>
            </div>
        </div>
        </div>

        <!-- body end-->
        <div id="goUp">
            <a href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'smooth');">Up</a>
        </div>
        <footer>
            &copy; 2019 Copyright The Invictus Code
            <br>
            theinvictuscode@gmail.com
            <br>
            KTM, Nepal
        </footer>
    </body>
</html>
<!-- scripts -->
<script src="{% static 'main/js/layout.js' %}"></script>
<script src="{% static 'main/js/validate.js' %}"></script>
<script type="text/javascript">
    function dispLogin()
    {
        SignUp=document.getElementById('SignUp');
        LogIn=document.getElementById('LogIn');

        LogIn.style.display = "block";
        SignUp.style.display = "none";
    }
    function dispSignup()
    {
        SignUp=document.getElementById('SignUp');
        LogIn=document.getElementById('LogIn');

        LogIn.style.display = "none";
        SignUp.style.display = "block";
    }
</script>
<!-- @yield('script') -->

user/templates/user/index.html
<!doctype html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>HamroFare</title>
        <link rel="icon" href="{% static 'main/pix/logo.png' %}">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/admin-layout.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/floating-labels.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/index.css' %}">
        
    </head>
    <body>
        <nav id="header">
            <div class="logo">
                <a href="#"><img src="{% static 'main/pix/logo.png' %}" alt="logo" id="logo"></a>
            </div>
            <div id="banner">
                Hamro<font id="bannerTitle">Fare</font>
            </div>
            <ul>
                <a href="{% url 'user:logout' %}"><li>LOGOUT</li></a>
            </ul>
        </nav>

        <!-- body -->
        <div class="container-fluid" id="wrapper">
        <div class="jumbotron" align="center">
            <div class="alert alert-success"><h1>Your Travel Partner</h1></div>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispTransaction()">Transaction</button>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispCard()">Card Status</button>
            <button class="btn btn-lg btn-outline-secondary" onclick="dispTopUP()">Balance TopUp</button>
            <div id="transaction">
                <br>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>S.N</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Distance Travelled</th>
                        <th>Fare</th>
                        <th>Vehicle Id</th>
                    </tr>
                {% for transaction in user.transaction_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ transaction.start}}</td>
                        <td>{{ transaction.end}}</td>
                        <td>{{ transaction.distance}}</td>
                        <td>{{ transaction.fare}}</td>
                        <td>{{ transaction.device_id}}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
            <div id="cardStatus">
                <br>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>S.N</th>
                        <th>Card Type</th>
                        <th>Created Date</th>
                        <th>Expiry Date</th>
                        <th>Balance</th>
                    </tr>
                {% for card in user.card_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ card.card_type}}</td>
                        <td>{{ card.created_date}}</td>
                        <td>{{ card.expiry_date}}</td>
                        <td>{{ card.balance}}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
            <div id="balanceTopUp">
                <br>
                <div class="alert alert-info">
                    <h2>Hey! you can top up your balance from this section.</h2>
                    <br>
                    <h3>You will be notified when this feature will be featured....</h3>
                </div>
            </div>

        </div>
        </div>

        <!-- body end-->
        <div id="goUp">
            <a href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'smooth');">Up</a>
        </div>
        <footer>
            &copy; 2019 Copyright The Invictus Code
            <br>
            theinvictuscode@gmail.com
            <br>
            KTM, Nepal
        </footer>
    </body>
</html>
<!-- scripts -->
<script src="{% static 'main/js/layout.js' %}"></script>
<script type="text/javascript">
    function dispTransaction()
    {
        transaction=document.getElementById('transaction');
        card=document.getElementById('cardStatus');
        balance=document.getElementById('balanceTopUp');

        transaction.style.display = "block";
        card.style.display = "none";
        balance.style.display = "none";
    }
    function dispCard()
    {
        transaction=document.getElementById('transaction');
        card=document.getElementById('cardStatus');
        balance=document.getElementById('balanceTopUp');

        transaction.style.display = "none";
        card.style.display = "block";
        balance.style.display = "none";
    }
    function dispTopUP()
    {
        transaction=document.getElementById('transaction');
        card=document.getElementById('cardStatus');
        balance=document.getElementById('balanceTopUp');

        transaction.style.display = "none";
        card.style.display = "none";
        balance.style.display = "block";
    }
</script>
<!-- @yield('script') -->